# Generated by Django 4.2.7 on 2023-11-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamifyApp', '0003_subscription_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
