# Generated by Django 4.2.7 on 2023-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamifyApp', '0006_remove_subscription_amount_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
